-- MySQL Script generated by MySQL Workbench
-- Сб 23 мар 2019 21:58:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
    'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE `mydb`;

-- -----------------------------------------------------
-- Table `mydb`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USERS`
(
  `ID`        INT          NOT NULL,
  `USER_NAME` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WORK_PERIODS_DAYS_AND_TIMES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WORK_PERIODS_DAYS_AND_TIMES`
(
  `WORK_SCHEDULES_ID` INT      NOT NULL,
  `START_DAY_TIME`    DATETIME NOT NULL,
  `END_DAY_TIME`      DATETIME NOT NULL,
  `PERIOD_MIN`        INT      NOT NULL,
  `USERS_ID`          INT      NOT NULL,
  PRIMARY KEY (`WORK_SCHEDULES_ID`),
  CONSTRAINT `fk_WORK_SCHEDULES_DAYS_AND_TIMES_USERS`
    FOREIGN KEY (`USERS_ID`)
      REFERENCES `mydb`.`USERS` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIES`
(
  `ID`          INT          NOT NULL,
  `NAME`        VARCHAR(256) NOT NULL,
  `DESCRIPTION` VARCHAR(256) NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WORK_PERIOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WORK_PERIOD`
(
  `ID`                                            INT          NOT NULL,
  `TIME_AMOUNT`                                   INT          NOT NULL,
  `DESCRIPTION`                                   VARCHAR(256) NULL,
  `WORK_PERIODS_DAYS_AND_TIMES_WORK_SCHEDULES_ID` INT          NOT NULL,
  `CATEGORIES_ID`                                 INT          NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_WORK_PERIOD_WORK_PERIODS_DAYS_AND_TIMES1_idx` (`WORK_PERIODS_DAYS_AND_TIMES_WORK_SCHEDULES_ID` ASC),
  INDEX `fk_WORK_PERIOD_CATEGORIES1_idx` (`CATEGORIES_ID` ASC),
  CONSTRAINT `fk_WORK_PERIOD_WORK_PERIODS_DAYS_AND_TIMES1`
    FOREIGN KEY (`WORK_PERIODS_DAYS_AND_TIMES_WORK_SCHEDULES_ID`)
      REFERENCES `mydb`.`WORK_PERIODS_DAYS_AND_TIMES` (`WORK_SCHEDULES_ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_WORK_PERIOD_CATEGORIES1`
    FOREIGN KEY (`CATEGORIES_ID`)
      REFERENCES `mydb`.`CATEGORIES` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
